name: habini
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_analytics: ^7.0.1
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^1.0.5
  animated_text_kit: ^4.2.1
  international_phone_input: ^1.0.4
  pinput: 1.0.0
  settings_ui: ^0.6.0
  timeago: ^2.0.27
  numberpicker: ^2.1.1
  flutter_spinkit: ^5.0.0
  google_fonts: ^2.1.0
  readmore: ^2.0.0
  firebase_messaging: ^11.2.0
  overlay_support: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

